"""Add cascade delete for users and allow null vendedor_id

Revision ID: 2366dc7b77e9
Revises: 2e00a1ffe322
Create Date: 2025-12-03 17:21:12.942870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2366dc7b77e9'
down_revision: Union[str, Sequence[str], None] = '2e00a1ffe322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agendamentos', 'vendedor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('agendamentos_vendedor_id_fkey'), 'agendamentos', type_='foreignkey')
    op.create_foreign_key(None, 'agendamentos', 'users', ['vendedor_id'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'MANAGER', 'VENDEDOR', 'ATENDENTE', 'suporte', name='userrole'),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('ADMIN', 'MANAGER', 'VENDEDOR', 'ATENDENTE', 'suporte', name='userrole'),
               existing_nullable=True)
    op.drop_constraint(None, 'agendamentos', type_='foreignkey')
    op.create_foreign_key(op.f('agendamentos_vendedor_id_fkey'), 'agendamentos', 'users', ['vendedor_id'], ['id'])
    op.alter_column('agendamentos', 'vendedor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
