"""remove_unique_constraint_from_clientes_cpf

Revision ID: 3cd6e25872bc
Revises: c57123ca3b57
Create Date: 2025-10-03 16:15:56.009885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cd6e25872bc'
down_revision: Union[str, Sequence[str], None] = 'c57123ca3b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clientes_cpf'), table_name='clientes')
    op.create_index(op.f('ix_clientes_cpf'), 'clientes', ['cpf'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clientes_cpf'), table_name='clientes')
    op.create_index(op.f('ix_clientes_cpf'), 'clientes', ['cpf'], unique=True)
    # ### end Alembic commands ###
