"""remove is_vip column from clientes

Revision ID: 4fc1baf0dd3e
Revises: 3cd6e25872bc
Create Date: 2025-10-10 13:57:06.586094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc1baf0dd3e'
down_revision: Union[str, Sequence[str], None] = '3cd6e25872bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'is_vip')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('is_vip', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
