"""Adicionar template_aniversario e enviar_aniversario

Revision ID: 504052496cdd
Revises: bf4b72589951
Create Date: 2026-01-05 18:43:59.190292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '504052496cdd'
down_revision: Union[str, Sequence[str], None] = 'bf4b72589951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_configs', sa.Column('template_aniversario', sa.Text(), nullable=True))
    op.add_column('whatsapp_configs', sa.Column('enviar_aniversario', sa.Boolean(), nullable=True, server_default='true'))

    # Atualiza registros existentes com valores padrão
    op.execute("UPDATE whatsapp_configs SET enviar_aniversario = true WHERE enviar_aniversario IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_configs', 'enviar_aniversario')
    op.drop_column('whatsapp_configs', 'template_aniversario')
    # ### end Alembic commands ###
