"""Change data_nascimento to data_aniversario with DD/MM format

Revision ID: 5be6e2f3794a
Revises: 504052496cdd
Create Date: 2026-01-05 22:14:09.760491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5be6e2f3794a'
down_revision: Union[str, Sequence[str], None] = '504052496cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Adicionar nova coluna
    op.add_column('clientes', sa.Column('data_aniversario', sa.String(length=5), nullable=True))

    # 2. Converter dados existentes de data_nascimento para data_aniversario (formato DD/MM)
    # Usa TO_CHAR para formatar a data como DD/MM
    op.execute("""
        UPDATE clientes
        SET data_aniversario = TO_CHAR(data_nascimento, 'DD/MM')
        WHERE data_nascimento IS NOT NULL
    """)

    # 3. Dropar coluna antiga
    op.drop_column('clientes', 'data_nascimento')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('data_nascimento', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('clientes', 'data_aniversario')
    # ### end Alembic commands ###
