"""Fix ALL foreign keys with CASCADE DELETE

Revision ID: 5c1318075a38
Revises: 87140fa28634
Create Date: 2025-12-03 17:41:53.422612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c1318075a38'
down_revision: Union[str, Sequence[str], None] = '87140fa28634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('configuracao_fidelidade_estabelecimento_id_fkey'), 'configuracao_fidelidade', type_='foreignkey')
    op.create_foreign_key(None, 'configuracao_fidelidade', 'estabelecimentos', ['estabelecimento_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('consumos_materiais_agendamento_id_fkey'), 'consumos_materiais', type_='foreignkey')
    op.drop_constraint(op.f('consumos_materiais_material_id_fkey'), 'consumos_materiais', type_='foreignkey')
    op.create_foreign_key(None, 'consumos_materiais', 'materiais', ['material_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'consumos_materiais', 'agendamentos', ['agendamento_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('materiais_estabelecimento_id_fkey'), 'materiais', type_='foreignkey')
    op.create_foreign_key(None, 'materiais', 'estabelecimentos', ['estabelecimento_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('premios_servico_id_fkey'), 'premios', type_='foreignkey')
    op.drop_constraint(op.f('premios_estabelecimento_id_fkey'), 'premios', type_='foreignkey')
    op.create_foreign_key(None, 'premios', 'estabelecimentos', ['estabelecimento_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'premios', 'servicos', ['servico_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('resgates_premios_premio_id_fkey'), 'resgates_premios', type_='foreignkey')
    op.drop_constraint(op.f('resgates_premios_cliente_id_fkey'), 'resgates_premios', type_='foreignkey')
    op.drop_constraint(op.f('resgates_premios_usado_em_agendamento_id_fkey'), 'resgates_premios', type_='foreignkey')
    op.create_foreign_key(None, 'resgates_premios', 'agendamentos', ['usado_em_agendamento_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'resgates_premios', 'premios', ['premio_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'resgates_premios', 'clientes', ['cliente_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('servicos_estabelecimento_id_fkey'), 'servicos', type_='foreignkey')
    op.create_foreign_key(None, 'servicos', 'estabelecimentos', ['estabelecimento_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servicos', type_='foreignkey')
    op.create_foreign_key(op.f('servicos_estabelecimento_id_fkey'), 'servicos', 'estabelecimentos', ['estabelecimento_id'], ['id'])
    op.drop_constraint(None, 'resgates_premios', type_='foreignkey')
    op.drop_constraint(None, 'resgates_premios', type_='foreignkey')
    op.drop_constraint(None, 'resgates_premios', type_='foreignkey')
    op.create_foreign_key(op.f('resgates_premios_usado_em_agendamento_id_fkey'), 'resgates_premios', 'agendamentos', ['usado_em_agendamento_id'], ['id'])
    op.create_foreign_key(op.f('resgates_premios_cliente_id_fkey'), 'resgates_premios', 'clientes', ['cliente_id'], ['id'])
    op.create_foreign_key(op.f('resgates_premios_premio_id_fkey'), 'resgates_premios', 'premios', ['premio_id'], ['id'])
    op.drop_constraint(None, 'premios', type_='foreignkey')
    op.drop_constraint(None, 'premios', type_='foreignkey')
    op.create_foreign_key(op.f('premios_estabelecimento_id_fkey'), 'premios', 'estabelecimentos', ['estabelecimento_id'], ['id'])
    op.create_foreign_key(op.f('premios_servico_id_fkey'), 'premios', 'servicos', ['servico_id'], ['id'])
    op.drop_constraint(None, 'materiais', type_='foreignkey')
    op.create_foreign_key(op.f('materiais_estabelecimento_id_fkey'), 'materiais', 'estabelecimentos', ['estabelecimento_id'], ['id'])
    op.drop_constraint(None, 'consumos_materiais', type_='foreignkey')
    op.drop_constraint(None, 'consumos_materiais', type_='foreignkey')
    op.create_foreign_key(op.f('consumos_materiais_material_id_fkey'), 'consumos_materiais', 'materiais', ['material_id'], ['id'])
    op.create_foreign_key(op.f('consumos_materiais_agendamento_id_fkey'), 'consumos_materiais', 'agendamentos', ['agendamento_id'], ['id'])
    op.drop_constraint(None, 'configuracao_fidelidade', type_='foreignkey')
    op.create_foreign_key(op.f('configuracao_fidelidade_estabelecimento_id_fkey'), 'configuracao_fidelidade', 'estabelecimentos', ['estabelecimento_id'], ['id'])
    # ### end Alembic commands ###
