"""Fix users estabelecimento_id FK with CASCADE

Revision ID: 69630dff9f56
Revises: cb166ed10d50
Create Date: 2025-12-03 17:50:09.486272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69630dff9f56'
down_revision: Union[str, Sequence[str], None] = 'cb166ed10d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_estabelecimento_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'estabelecimentos', ['estabelecimento_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_estabelecimento_id_fkey'), 'users', 'estabelecimentos', ['estabelecimento_id'], ['id'])
    # ### end Alembic commands ###
