"""add deleted_at to agendamentos for soft delete

Revision ID: 6bf454cefd76
Revises: ff77f1a3d468
Create Date: 2025-11-17 18:58:28.585545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bf454cefd76'
down_revision: Union[str, Sequence[str], None] = 'ff77f1a3d468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agendamentos', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('configuracao_fidelidade', 'reais_por_ponto',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Valor em reais para ganhar 1 ponto (ex: 100.00 = R$ 100 = 1 ponto)',
               existing_comment='Valor em reais para ganhar 1 ponto',
               existing_nullable=False)
    op.alter_column('configuracao_fidelidade', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('configuracao_fidelidade', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_configuracao_fidelidade_id'), 'configuracao_fidelidade', ['id'], unique=False)
    op.alter_column('premios', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('premios', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_premios_id'), 'premios', ['id'], unique=False)
    op.alter_column('resgates_premios', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('resgates_premios', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_resgates_premios_id'), 'resgates_premios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resgates_premios_id'), table_name='resgates_premios')
    op.alter_column('resgates_premios', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('resgates_premios', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_premios_id'), table_name='premios')
    op.alter_column('premios', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('premios', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_configuracao_fidelidade_id'), table_name='configuracao_fidelidade')
    op.alter_column('configuracao_fidelidade', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('configuracao_fidelidade', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('configuracao_fidelidade', 'reais_por_ponto',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Valor em reais para ganhar 1 ponto',
               existing_comment='Valor em reais para ganhar 1 ponto (ex: 100.00 = R$ 100 = 1 ponto)',
               existing_nullable=False)
    op.drop_column('agendamentos', 'deleted_at')
    # ### end Alembic commands ###
