"""Add cascade delete for clientes on estabelecimento delete

Revision ID: 7c8fded51055
Revises: 2366dc7b77e9
Create Date: 2025-12-03 17:32:30.031999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c8fded51055'
down_revision: Union[str, Sequence[str], None] = '2366dc7b77e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('clientes_estabelecimento_id_fkey'), 'clientes', type_='foreignkey')
    op.create_foreign_key(None, 'clientes', 'estabelecimentos', ['estabelecimento_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.create_foreign_key(op.f('clientes_estabelecimento_id_fkey'), 'clientes', 'estabelecimentos', ['estabelecimento_id'], ['id'])
    # ### end Alembic commands ###
