"""Add cascade delete for agendamentos FKs

Revision ID: 87140fa28634
Revises: 7c8fded51055
Create Date: 2025-12-03 17:36:33.324849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87140fa28634'
down_revision: Union[str, Sequence[str], None] = '7c8fded51055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agendamentos_servico_id_fkey'), 'agendamentos', type_='foreignkey')
    op.drop_constraint(op.f('agendamentos_cliente_id_fkey'), 'agendamentos', type_='foreignkey')
    op.drop_constraint(op.f('agendamentos_estabelecimento_id_fkey'), 'agendamentos', type_='foreignkey')
    op.create_foreign_key(None, 'agendamentos', 'clientes', ['cliente_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'agendamentos', 'estabelecimentos', ['estabelecimento_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'agendamentos', 'servicos', ['servico_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agendamentos', type_='foreignkey')
    op.drop_constraint(None, 'agendamentos', type_='foreignkey')
    op.drop_constraint(None, 'agendamentos', type_='foreignkey')
    op.create_foreign_key(op.f('agendamentos_estabelecimento_id_fkey'), 'agendamentos', 'estabelecimentos', ['estabelecimento_id'], ['id'])
    op.create_foreign_key(op.f('agendamentos_cliente_id_fkey'), 'agendamentos', 'clientes', ['cliente_id'], ['id'])
    op.create_foreign_key(op.f('agendamentos_servico_id_fkey'), 'agendamentos', 'servicos', ['servico_id'], ['id'])
    # ### end Alembic commands ###
