"""add lembrete enviado to agendamentos

Revision ID: bedb031cc445
Revises: f67d53028a98
Create Date: 2025-12-15 19:30:21.777035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bedb031cc445'
down_revision: Union[str, Sequence[str], None] = 'f67d53028a98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agendamentos', sa.Column('lembrete_enviado', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agendamentos', 'lembrete_enviado')
    # ### end Alembic commands ###
