"""add_estabelecimento_id_to_clientes

Revision ID: c57123ca3b57
Revises: 5ea6e951a203
Create Date: 2025-10-03 16:05:11.367444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c57123ca3b57'
down_revision: Union[str, Sequence[str], None] = '5ea6e951a203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('estabelecimento_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clientes', 'estabelecimentos', ['estabelecimento_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clientes', type_='foreignkey')
    op.drop_column('clientes', 'estabelecimento_id')
    # ### end Alembic commands ###
