"""Fix empresa_id FK with CASCADE DELETE

Revision ID: cb166ed10d50
Revises: 5c1318075a38
Create Date: 2025-12-03 17:46:13.339862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb166ed10d50'
down_revision: Union[str, Sequence[str], None] = '5c1318075a38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('estabelecimentos_empresa_id_fkey'), 'estabelecimentos', type_='foreignkey')
    op.create_foreign_key(None, 'estabelecimentos', 'empresas', ['empresa_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'estabelecimentos', type_='foreignkey')
    op.create_foreign_key(op.f('estabelecimentos_empresa_id_fkey'), 'estabelecimentos', 'empresas', ['empresa_id'], ['id'])
    # ### end Alembic commands ###
