"""add recycling fields to whatsapp config

Revision ID: f67d53028a98
Revises: 8b32d1d811f3
Create Date: 2025-12-15 19:17:31.058859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f67d53028a98'
down_revision: Union[str, Sequence[str], None] = '8b32d1d811f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notificacoes_log_agendamento_id'), table_name='notificacoes_log')
    op.drop_index(op.f('ix_notificacoes_log_config_id'), table_name='notificacoes_log')
    op.drop_index(op.f('ix_notificacoes_log_status'), table_name='notificacoes_log')
    op.drop_table('notificacoes_log')
    op.drop_index(op.f('ix_notificacoes_templates_config_id'), table_name='notificacoes_templates')
    op.drop_index(op.f('ix_notificacoes_templates_tipo'), table_name='notificacoes_templates')
    op.drop_table('notificacoes_templates')
    op.drop_index(op.f('ix_notificacoes_config_estabelecimento_id'), table_name='notificacoes_config')
    op.drop_table('notificacoes_config')
    op.add_column('whatsapp_configs', sa.Column('meses_inatividade', sa.Integer(), nullable=True))
    op.add_column('whatsapp_configs', sa.Column('link_agendamento', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_configs', 'link_agendamento')
    op.drop_column('whatsapp_configs', 'meses_inatividade')
    op.create_table('notificacoes_config',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('notificacoes_config_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('estabelecimento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('whatsapp_numero', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('notificacoes_habilitadas', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('enviar_confirmacao', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('enviar_lembrete_1dia', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('enviar_lembrete_1hora', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('enviar_agradecimento', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('enviar_cancelamento', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], name='notificacoes_config_estabelecimento_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='notificacoes_config_pkey'),
    sa.UniqueConstraint('estabelecimento_id', name='notificacoes_config_estabelecimento_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_notificacoes_config_estabelecimento_id'), 'notificacoes_config', ['estabelecimento_id'], unique=False)
    op.create_table('notificacoes_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('config_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mensagem', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['notificacoes_config.id'], name=op.f('notificacoes_templates_config_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notificacoes_templates_pkey'))
    )
    op.create_index(op.f('ix_notificacoes_templates_tipo'), 'notificacoes_templates', ['tipo'], unique=False)
    op.create_index(op.f('ix_notificacoes_templates_config_id'), 'notificacoes_templates', ['config_id'], unique=False)
    op.create_table('notificacoes_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('config_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('agendamento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('destinatario', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('remetente', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('mensagem', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('erro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('enviado_em', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamentos.id'], name=op.f('notificacoes_log_agendamento_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['config_id'], ['notificacoes_config.id'], name=op.f('notificacoes_log_config_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notificacoes_log_pkey'))
    )
    op.create_index(op.f('ix_notificacoes_log_status'), 'notificacoes_log', ['status'], unique=False)
    op.create_index(op.f('ix_notificacoes_log_config_id'), 'notificacoes_log', ['config_id'], unique=False)
    op.create_index(op.f('ix_notificacoes_log_agendamento_id'), 'notificacoes_log', ['agendamento_id'], unique=False)
    # ### end Alembic commands ###
