"""add meta template names to whatsapp config

Revision ID: f9c6017116f8
Revises: bedb031cc445
Create Date: 2025-12-15 23:01:40.675340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c6017116f8'
down_revision: Union[str, Sequence[str], None] = 'bedb031cc445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_configs', sa.Column('meta_template_agendamento', sa.String(length=255), nullable=True))
    op.add_column('whatsapp_configs', sa.Column('meta_template_lembrete', sa.String(length=255), nullable=True))
    op.add_column('whatsapp_configs', sa.Column('meta_template_confirmacao', sa.String(length=255), nullable=True))
    op.add_column('whatsapp_configs', sa.Column('meta_template_cancelamento', sa.String(length=255), nullable=True))
    op.add_column('whatsapp_configs', sa.Column('meta_template_reciclagem', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_configs', 'meta_template_reciclagem')
    op.drop_column('whatsapp_configs', 'meta_template_cancelamento')
    op.drop_column('whatsapp_configs', 'meta_template_confirmacao')
    op.drop_column('whatsapp_configs', 'meta_template_lembrete')
    op.drop_column('whatsapp_configs', 'meta_template_agendamento')
    # ### end Alembic commands ###
